<a href="https://colab.research.google.com/github/Nazneen-akram/healthcare-insurance-fraud/blob/main/EDA_health_insurance_V1_02JAN2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
# Load the datasets
data_paths = {
    "inpatient_train_data": "Train_Inpatientdata-1542865627584.csv",
    "outpatient_train_data": "Train_Outpatientdata-1542865627584.csv",
    "beneficiary_train_data": "Train_Beneficiarydata-1542865627584.csv",
    "provider_train_data": "Train-1542865627584.csv",
    "inpatient_test_data": "Test_Inpatientdata-1542969243754.csv",
    "outpatient_test_data": "Test_Outpatientdata-1542969243754.csv",
    "beneficiary_test_data": "Test_Beneficiarydata-1542969243754.csv",
    "provider_test_data": "Test-1542969243754.csv",
}

In [28]:
# Load datasets into a dictionary of dataframes
dataframes = {}
for key, value in data_paths.items():
    try:
        dataframes[key] = pd.read_csv(value, on_bad_lines='skip', delimiter=',')
    except pd.errors.ParserError:
        print(f"Error parsing {value}. Please check the file format.")

In [38]:
# Perform EDA on each dataset
for dataset_name, df in dataframes.items():
    print(f"Exploring {dataset_name} Dataset")
    # Basic information about the dataset
    df.info()

    # Descriptive statistics for numerical features
    #df.describe()

Exploring inpatient_train_data Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40474 entries, 0 to 40473
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   BeneID                  40474 non-null  object
 1   ClaimID                 40474 non-null  object
 2   ClaimStartDt            40474 non-null  object
 3   ClaimEndDt              40474 non-null  object
 4   Provider                40474 non-null  object
 5   InscClaimAmtReimbursed  40474 non-null  int64
 6   AttendingPhysician      40362 non-null  object
 7   OperatingPhysician      23830 non-null  object
 8   OtherPhysician          4690 non-null   object
 9   AdmissionDt             40474 non-null  object
 10  ClmAdmitDiagnosisCode   40474 non-null  object
 11  DeductibleAmtPaid       39575 non-null  float64
 12  DischargeDt             40474 non-null  object
 13  DiagnosisGroupCode      40474 non-null  object
 14  ClmDiagnosisCode_1      40474 non-null  object
 15  ClmDiagnosisCode_2      40248 non-null  object
 16  ClmDiagnosisCode_3      39798 non-null  object
 17  ClmDiagnosisCode_4      38940 non-null  object
 18  ClmDiagnosisCode_5      37580 non-null  object
 19  ClmDiagnosisCode_6      35636 non-null  object
 20  ClmDiagnosisCode_7      33216 non-null  object
 21  ClmDiagnosisCode_8      30532 non-null  object
 22  ClmDiagnosisCode_9      26977 non-null  object
 23  ClmDiagnosisCode_10     3927 non-null   object
 24  ClmProcedureCode_1      23148 non-null  float64
 25  ClmProcedureCode_2      5454 non-null   float64
 26  ClmProcedureCode_3      965 non-null    float64
 27  ClmProcedureCode_4      116 non-null    float64
 28  ClmProcedureCode_5      9 non-null      float64
 29  ClmProcedureCode_6      0 non-null      float64
dtypes: float64(7), int64(1), object(22)
memory usage: 9.3+ MB
Exploring outpatient_train_data Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517737 entries, 0 to 517736
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   BeneID                  517737 non-null  object
 1   ClaimID                 517737 non-null  object
 2   ClaimStartDt            517737 non-null  object
 3   ClaimEndDt              517737 non-null  object
 4   Provider                517737 non-null  object
 5   InscClaimAmtReimbursed  517737 non-null  int64
 6   AttendingPhysician      516341 non-null  object
 7   OperatingPhysician      90617 non-null   object
 8   OtherPhysician          195046 non-null  object
 9   ClmDiagnosisCode_1      507284 non-null  object
 10  ClmDiagnosisCode_2      322357 non-null  object
 11  ClmDiagnosisCode_3      203257 non-null  object
 12  ClmDiagnosisCode_4      125596 non-null  object
 13  ClmDiagnosisCode_5      74344 non-null   object
 14  ClmDiagnosisCode_6      48756 non-null   object
 15  ClmDiagnosisCode_7      32961 non-null   object
 16  ClmDiagnosisCode_8      22912 non-null   object
 17  ClmDiagnosisCode_9      14838 non-null   object
 18  ClmDiagnosisCode_10     1083 non-null    object
 19  ClmProcedureCode_1      162 non-null     float64
 20  ClmProcedureCode_2      36 non-null      float64
 21  ClmProcedureCode_3      4 non-null       float64
 22  ClmProcedureCode_4      2 non-null       float64
 23  ClmProcedureCode_5      0 non-null       float64
 24  ClmProcedureCode_6      0 non-null       float64
 25  DeductibleAmtPaid       517737 non-null  int64
 26  ClmAdmitDiagnosisCode   105425 non-null  object
dtypes: float64(6), int64(2), object(19)
memory usage: 106.7+ MB
Exploring beneficiary_train_data Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138556 entries, 0 to 138555
Data columns (total 25 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   BeneID                           138556 non-null  object
 1   DOB                              138556 non-null  object
 2   DOD                              1421 non-null    object
 3   Gender                           138556 non-null  int64
 4   Race                             138556 non-null  int64
 5   RenalDiseaseIndicator            138556 non-null  object
 6   State                            138556 non-null  int64
 7   County                           138556 non-null  int64
 8   NoOfMonths_PartACov              138556 non-null  int64
 9   NoOfMonths_PartBCov              138556 non-null  int64
 10  ChronicCond_Alzheimer            138556 non-null  int64
 11  ChronicCond_Heartfailure         138556 non-null  int64
 12  ChronicCond_KidneyDisease        138556 non-null  int64
 13  ChronicCond_Cancer               138556 non-null  int64
 14  ChronicCond_ObstrPulmonary       138556 non-null  int64
 15  ChronicCond_Depression           138556 non-null  int64
 16  ChronicCond_Diabetes             138556 non-null  int64
 17  ChronicCond_IschemicHeart        138556 non-null  int64
 18  ChronicCond_Osteoporasis         138556 non-null  int64
 19  ChronicCond_rheumatoidarthritis  138556 non-null  int64
 20  ChronicCond_stroke               138556 non-null  int64
 21  IPAnnualReimbursementAmt         138556 non-null  int64
 22  IPAnnualDeductibleAmt            138556 non-null  int64
 23  OPAnnualReimbursementAmt         138556 non-null  int64
 24  OPAnnualDeductibleAmt            138556 non-null  int64
dtypes: int64(21), object(4)
memory usage: 26.4+ MB
Exploring provider_train_data Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5410 entries, 0 to 5409
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Provider        5410 non-null   object
 1   PotentialFraud  5410 non-null   object
dtypes: object(2)
memory usage: 84.7+ KB
Exploring inpatient_test_data Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   BeneID                  9551 non-null   object
 1   ClaimID                 9551 non-null   object
 2   ClaimStartDt            9551 non-null   object
 3   ClaimEndDt              9551 non-null   object
 4   Provider                9551 non-null   object
 5   InscClaimAmtReimbursed  9551 non-null   int64
 6   AttendingPhysician      9520 non-null   object
 7   OperatingPhysician      5589 non-null   object
 8   OtherPhysician          1013 non-null   object
 9   AdmissionDt             9551 non-null   object
 10  ClmAdmitDiagnosisCode   9551 non-null   object
 11  DeductibleAmtPaid       9355 non-null   float64
 12  DischargeDt             9551 non-null   object
 13  DiagnosisGroupCode      9551 non-null   object
 14  ClmDiagnosisCode_1      9551 non-null   object
 15  ClmDiagnosisCode_2      9497 non-null   object
 16  ClmDiagnosisCode_3      9382 non-null   object
 17  ClmDiagnosisCode_4      9147 non-null   object
 18  ClmDiagnosisCode_5      8832 non-null   object
 19  ClmDiagnosisCode_6      8354 non-null   object
 20  ClmDiagnosisCode_7      7815 non-null   object
 21  ClmDiagnosisCode_8      7191 non-null   object
 22  ClmDiagnosisCode_9      6313 non-null   object
 23  ClmDiagnosisCode_10     887 non-null    object
 24  ClmProcedureCode_1      5433 non-null   float64
 25  ClmProcedureCode_2      1254 non-null   float64
 26  ClmProcedureCode_3      223 non-null    float64
 27  ClmProcedureCode_4      29 non-null     float64
 28  ClmProcedureCode_5      2 non-null      float64
 29  ClmProcedureCode_6      0 non-null      float64
dtypes: float64(7), int64(1), object(22)
memory usage: 2.2+ MB
Exploring outpatient_test_data Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125841 entries, 0 to 125840
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   BeneID                  125841 non-null  object
 1   ClaimID                 125841 non-null  object
 2   ClaimStartDt            125841 non-null  object
 3   ClaimEndDt              125841 non-null  object
 4   Provider                125841 non-null  object
 5   InscClaimAmtReimbursed  125841 non-null  int64
 6   AttendingPhysician      125525 non-null  object
 7   OperatingPhysician      21604 non-null   object
 8   OtherPhysician          47619 non-null   object
 9   ClmDiagnosisCode_1      123263 non-null  object
 10  ClmDiagnosisCode_2      78110 non-null   object
 11  ClmDiagnosisCode_3      49266 non-null   object
 12  ClmDiagnosisCode_4      30470 non-null   object
 13  ClmDiagnosisCode_5      17966 non-null   object
 14  ClmDiagnosisCode_6      11806 non-null   object
 15  ClmDiagnosisCode_7      7970 non-null    object
 16  ClmDiagnosisCode_8      5531 non-null    object
 17  ClmDiagnosisCode_9      3563 non-null    object
 18  ClmDiagnosisCode_10     263 non-null     object
 19  ClmProcedureCode_1      34 non-null      float64
 20  ClmProcedureCode_2      9 non-null       float64
 21  ClmProcedureCode_3      2 non-null       float64
 22  ClmProcedureCode_4      0 non-null       float64
 23  ClmProcedureCode_5      0 non-null       float64
 24  ClmProcedureCode_6      0 non-null       float64
 25  DeductibleAmtPaid       125841 non-null  int64
 26  ClmAdmitDiagnosisCode   25805 non-null   object
dtypes: float64(6), int64(2), object(19)
memory usage: 25.9+ MB
Exploring beneficiary_test_data Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63968 entries, 0 to 63967
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   BeneID                           63968 non-null  object
 1   DOB                              63968 non-null  object
 2   DOD                              574 non-null    object
 3   Gender                           63968 non-null  int64
 4   Race                             63968 non-null  int64
 5   RenalDiseaseIndicator            63968 non-null  object
 6   State                            63968 non-null  int64
 7   County                           63968 non-null  int64
 8   NoOfMonths_PartACov              63968 non-null  int64
 9   NoOfMonths_PartBCov              63968 non-null  int64
 10  ChronicCond_Alzheimer            63968 non-null  int64
 11  ChronicCond_Heartfailure         63968 non-null  int64
 12  ChronicCond_KidneyDisease        63968 non-null  int64
 13  ChronicCond_Cancer               63968 non-null  int64
 14  ChronicCond_ObstrPulmonary       63968 non-null  int64
 15  ChronicCond_Depression           63968 non-null  int64
 16  ChronicCond_Diabetes             63968 non-null  int64
 17  ChronicCond_IschemicHeart        63968 non-null  int64
 18  ChronicCond_Osteoporasis         63968 non-null  int64
 19  ChronicCond_rheumatoidarthritis  63968 non-null  int64
 20  ChronicCond_stroke               63968 non-null  int64
 21  IPAnnualReimbursementAmt         63968 non-null  int64
 22  IPAnnualDeductibleAmt            63968 non-null  int64
 23  OPAnnualReimbursementAmt         63968 non-null  int64
 24  OPAnnualDeductibleAmt            63968 non-null  int64
dtypes: int64(21), object(4)
memory usage: 12.2+ MB
Exploring provider_test_data Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1353 entries, 0 to 1352
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Provider  1353 non-null   object
dtypes: object(1)
memory usage: 10.7+ KB